version: "3.8"

services:
  vulnerable_redirect:
    build:
      context: ./vulnerable_redirect
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: vulnerable_redirect

  admin_server:
    build:
      context: ./admin_server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: admin_server
