version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_ssrf
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_ssrf
    ports:
      - "8080:80"
    depends_on:
      - redis

volumes:
  redis-data:
